import { StyleSheet, Dimensions } from "react-native";
const width = Dimensions.get("window").width;
const height = Dimensions.get("window").height;
import { NativeModules } from "react-native";
const { StatusBarManager } = NativeModules;
const heightStatus = StatusBarManager.HEIGHT;

const colors = {
  backgroundPanel: "#10AC84",
  backgroundColor: "#FCFCFC",
  backgroundGeneral: "#0074E4",
  primary: "#2199F5",
  secondary: "#263238",
  default: "#FFFFFF",
  info: "#2055eb",
  success: "#2E7D32",
  warnning: "#fffb9e",
  error: "#ec5a65",
  black: "#000000",
  cuadrosColorMarcar: "#EEEEEE",
  botones_bg_color: "#3652AD",
  botones_tx_color: "#FFFF",
  botones_bg_color_sec: "#0C3A6E",
};

const login_s = StyleSheet.create({
  image: {
    alignSelf: "center",
    width: width * 1,
    height: height * 0.25,
    backgroundColor: "white",
    borderBottomRightRadius: 200,
    borderBottomLeftRadius: 200,
  },
  containerLogin: {
    height: height * 1000,
    // flex: 1,
    backgroundColor: "white",
  },
  cabeceraFoto: {
    height: height * 0.32,
    justifyContent: "center",
    flexDirection: "column",
    // backgroundColor:'#67D1DB', //10AC84
    // borderBottomLeftRadius:100,
    borderBottomEndRadius: 200,
    borderBottomStartRadius: 200,
    borderBottomRightRadius: 100,

    // backgroundColor:'#3E64FF'
  },
  espaciador: {
    height: height * 0.1,
    width: width * 0.92,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor:'#3E64FF'
    // alignContent:'center',
    // backgroundColor:'#C3ACD0'
  },
  espaciador2: {
    height: height * 0.03,
    width: width * 0.92,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  containerInputs: {
    height: height * 0.25,
    alignItems: "center",
    width: "100%",
    flexDirection: "column",
    justifyContent: "center",
    // backgroundColor:'#B4B5B5'
  },
  containerInputs_registro: {
    height: height * 0.15,
    alignItems: "center",
    width: "100%",
    // backgroundColor:'#F1D88D',
    // justifyContent:'center',
    flexDirection: "column",
  },
  titulo: {
    fontWeight: "800",
    fontSize: 21,
    color: "#10AC84",
  },
  subTitulo: {
    fontWeight: "500",
    fontSize: 18,
    color: "#6F7579",
  },
  textInputs: {
    textAlign: "left",
    alignSelf: "center",
    width: width * 0.92,
    // backgroundColor:'#000'
  },
  containerInputUsuario: {
    // borderWidth:0.5,
    borderRadius: 200,
    borderWidth: 0.4,
    borderColor: "#364E68",
    alignItems: "center",
    width: width * 0.92,
    height: height * 0.07,
    margin: 10,
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  containerInputContraseña: {
    // borderWidth:0.5,
    borderRadius: 200,
    borderWidth: 0.4,
    borderColor: "#364E68",
    alignItems: "center",
    width: width * 0.92,
    height: height * 0.07,
    margin: 10,
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  textInput: {
    width: width * 0.6,
  },
  espaciador2: {
    height: height * 0.01,
    width: width * 0.92,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    // alignContent:'center',
    // backgroundColor:'#C3ACD0'
  },
  containerBoton: {
    width: "100%",
    height: height * 0.23,
    width: width * 0.92,
    alignSelf: "center",
    // backgroundColor:'#E8E2E2',
    justifyContent: "flex-start",
    // marginBottom:( height * 0.050)
  },
  buttonIngresar: {
    // width: width * 0.92,
    borderRadius: 20,
    height: height * 0.070,
    flexDirection:'row',
    justifyContent:'center',
    alignItems:'center',
    backgroundColor: colors.backgroundPanel
    },
  buttonIngresar_text:{
    fontSize:16.5,
    color:'#ffff'

  },
  footer: {
    flexDirection: "row",
    height: height * 0.07,
    // backgroundColor:'red',
    justifyContent: "center",
    alignItems: "center",
    position: "relative", //Here is the trick
    bottom: 0,
  },
  image_footer: {
    width: width * 0.25,
    height: height * 0.05,
  },
});

const recuperar_password = StyleSheet.create({
  image: {
    alignSelf: "center",
    width: width * 0.87,
    height: height * 0.28,
  },
  containerLogin: {
    height: height * 1000,
    // flex: 1,
    backgroundColor: "white",
  },
  cabeceraFoto: {
    height: height * 0.35,
    justifyContent: "center",
    flexDirection: "column",
    // backgroundColor:'#3E64FF'
  },
  espaciador: {
    height: height * 0.1,
    width: width * 0.92,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  containerInputs: {
    height: height * 0.27,
    alignItems: "center",
    width: "100%",
    flexDirection: "column",
  },
  containerInputs_registro: {
    height: height * 0.12,
    alignItems: "center",
    width: "100%",
    // backgroundColor:'#F1D88D',
    // justifyContent:'center',
    flexDirection: "column",
  },
  titulo: {
    fontWeight: "500",
    fontSize: 19,
    color: "#606470",
  },
  textInputs: {
    textAlign: "left",
    alignSelf: "center",
    width: width * 0.92,
    // backgroundColor:'#000'
  },
  containerInputUsuario: {
    borderWidth: 0.5,
    borderRadius: 200,
    borderColor: "#364E68",
    alignItems: "center",
    width: width * 0.92,
    height: height * 0.07,
    margin: 10,
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  containerInputContraseña: {
    borderWidth: 0.5,
    borderRadius: 200,
    borderColor: "#364E68",
    alignItems: "center",
    width: width * 0.92,
    height: height * 0.07,
    margin: 10,
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  textInput: {
    width: width * 0.72,
  },
  espaciador2: {
    height: height * 0.01,
    width: width * 0.92,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    // alignContent:'center',
    // backgroundColor:'#C3ACD0'
  },
  containerBoton: {
    width: "100%",
    height: height * 0.23,
    width: width * 0.92,
    alignSelf: "center",
    // backgroundColor:'#E8E2E2',
    justifyContent: "flex-start",
    // marginBottom:( height * 0.050)
  },
  buttonIngresar: {
    width: width * 0.92,
    borderRadius: 10,
  },
  footer: {
    flexDirection: "row",
    height: height * 0.07,
    // backgroundColor:'red',
    justifyContent: "center",
    alignItems: "center",
    position: "relative", //Here is the trick
    bottom: 0,
  },
});

const registro = StyleSheet.create({
  image: {
    alignSelf: "center",
    width: width * 0.7,
    height: height * 0.27,
  },
  containerLogin: {
    height: height * 1000,
    width: width * 1,
    backgroundColor: "white",
  },
  cabeceraFoto: {
    height: height * 0.3,
    justifyContent: "center",
    flexDirection: "column",
    // backgroundColor:'#3E64FF'
  },
  containerInputs: {
    height: height * 0.53,
    alignItems: "center",
    width: "100%",
    // backgroundColor:'#F1D88D',
    // justifyContent:'center',
    flexDirection: "column",
  },
  sexo: {
    flexDirection: "row",
    // alignContent:'space-between',
    width: width * 0.9,
    // backgroundColor:'tomato'
  },
  titulo: {
    fontWeight: "bold",
    fontSize: 19,
    bottom: 20,
    marginTop: 20,
    color: "#606470",
  },
  textInputs: {
    textAlign: "left",
    alignSelf: "center",
    width: width * 0.92,
  },
  containerInputUsuario: {
    borderWidth: 0.5,
    borderRadius: 200,
    borderColor: "#364E68",
    alignItems: "center",
    width: width * 0.92,
    height: height * 0.07,
    margin: 10,
    flexDirection: "row",
    justifyContent: "space-around",
  },
  containerInputContraseña: {
    borderWidth: 0.5,
    borderRadius: 200,
    borderColor: "#364E68",
    alignItems: "center",
    width: width * 0.92,
    height: height * 0.07,
    margin: 10,
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  textInput: {
    width: width * 0.82,
  },
  textInputContrasena: {
    width: width * 0.75,
  },
  containerBoton: {
    width: "100%",
    height: height * 0.07,
    width: width * 0.92,
    alignSelf: "center",
    // backgroundColor:'tomato',
    justifyContent: "flex-start",
    // marginBottom:( height * 0.050)
  },
  buttonIngresar: {
    width: width * 0.92,
    borderRadius: 10,
  },
  footer: {
    flexDirection: "row",
    height: height * 0.07,
    // backgroundColor:'red',
    justifyContent: "center",
    alignItems: "center",
  },
});

const menu_index = StyleSheet.create({
  contenedor: {
    backgroundColor: colors.backgroundColor,
    alignItems: "center",
    height: height,
    flex: 1,
  },
  espaciador: {
    height: heightStatus,
    // backgroundColor: '#10AC84',
    width: width * 1,
  },
  detalle_usuario: {
    height: height * 0.14,
    width: width * 1,
    // justifyContent:'space-around',
    alignItems: "center",
    backgroundColor: colors.backgroundColor,
    flexDirection: "column",
    borderBottomEndRadius: 20,
    borderBottomStartRadius: 20,
  },
  fila1: {
    width: width * 0.9,
    height: height * 0.08,
    // backgroundColor: 'red',
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    borderColor: "white",
    // borderWidth:.4,
    borderRadius: 20,
  },
  fila2: {
    width: width * 0.9,
    height: height * 0.04,
    // backgroundColor: 'green',
    flexDirection: "row",
  },
  menu_titulo_container: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    width: width * 0.9,
    marginBottom: height * 0.005,
    backgroundColor: "#EEEEEE",
  },
  menu_titulo_asistencia: {
    fontSize: 15,
    color: "#343434",
    fontWeight: "400",
  },
  detalle_usuario_c1: {
    width: width * 0.16,
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },
  imagen_logo: {
    width: 45,
    height: 45,
    borderWidth: 1,
    borderRadius: 10,
  },
  detalle_usuario_c2: {
    backgroundColor: "#FFFFFF",
    width: width * 0.11,
    height: height * 0.05,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#FCFCFC",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  titulo: {
    fontSize: 18,
    fontWeight: "500",
    color: "#214151",
  },
  subtitulo: {
    fontSize: 19,
    fontWeight: "600",
    color: "#214151",
  },
  detalle_usuario_c3: {
    // backgroundColor: 'yellow',
    width: width * 0.9,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  cuerpoMedio: {
    backgroundColor: "#ffff",
    height: height * 0.88,
    width: width * 1,
    borderTopEndRadius: 30,
    borderTopStartRadius: 30,
    alignItems: "center",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#FCFCFC",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  menu_grid: {
    height: height * 0.13,
    width: width * 0.85,
    // backgroundColor:'red',
    alignSelf: "center",
  },
  Campo: {
    flexDirection: "row",
    width: width * 0.85,
    height: height * 0.13,
    marginBottom: 20,
    justifyContent: "space-around",
    // backgroundColor:'#F3F3F3'
  },
  imagen_menu: {
    width: width * 0.1,
    height: height * 0.05,
    top: 5,
  },
  contorno_img: {
    width: width * 0.15,
    height: height * 0.065,
    // justifyContent:'flex-end',
    //F8F0DF
    backgroundColor: "#FCFCFC",
    alignItems: "center",
    // alignItems:'stretch',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: "#EEF2F5",
    alignItems: "center",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#FCFCFC",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    // borderColor:'#E1EEDD'
  },
  // MODAL
  modal_container_gps: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  modal_container_gps_contenedor: {
    width: width * 1,
    justifyContent: "center",
    alignSelf: "flex-end",
    borderRadius: 5,
    borderTopEndRadius: 10,
    borderTopLeftRadius: 10,
    backgroundColor: "#FFFF",
  },
  modal_container_gps_contenedor_cuerpo: {
    width: width * 0.95,
    justifyContent: "center",
    alignSelf: "center",
    borderRadius: 5,
    // backgroundColor: "#FFFF",
  },
  modal_container_gps_option: {
    height: height * 0.07,
    justifyContent: "center",
    width: width * 0.95,
    alignItems: "stretch",
    backgroundColor: "#FFFF",
  },
  modal_container_gps_option_boton: {
    width: width * 0.78,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    alignContent: "space-around",
  },
  text_modal: {
    fontSize: 14.5,
    fontWeight: "400",
    color: "#4B4B4B",
  },
  text_modal_boton: {
    fontSize: 14.6,
    color: "#214151",
    // paddingLeft:5
  },
  text_modal_tabla: {
    fontSize: 14.4,
    color: "#495464",
  },
  // MODAL
  buttonText: {
    // backgroundColor:'#3366FF',
    borderRadius: 5,
    top: 10,
    color: "#000",
    textAlign: "center",
    fontSize: 13,
  },
  menu_central: {
    height: height * 0.3,
    width: width * 0.95,
    marginBottom: height * 0.015,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFFF",
    borderRadius: 5,
    borderWidth: 0.5,
    borderColor: "#E1E1E1",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  menu_central_fila: {
    flexDirection: "row",
    // backgroundColor:'red',
    width: width * 0.9,
    borderBottomWidth: 1,
    borderBottomColor: "#B4B4B8",
    height: height * 0.04,
    justifyContent: "flex-start",
    alignItems: "center",
  },
  menu_central_fila_rows: {
    flexDirection: "row",
    width: width * 0.9,
    backgroundColor: "#F9FCFB",
    height: height * 0.055,
    justifyContent: "center",
    alignItems: "center",
  },
  menu_central_columnas: {
    width: width * 0.4,
    alignItems: "flex-start",
  },
  menu_central_columnas_dias: {
    width: width * 0.1,
    justifyContent: "center",
    alignItems: "center",
  },

  slider: {
    height: height * 0.22,
    width: width * 0.95,
    alignSelf: "center",
    // backgroundColor:'tomato',
  },
  imagen_slider: {
    height: height * 0.2,
    width: width * 0.9,
    borderRadius: 15,
    resizeMode: "contain",
  },
  textoSlider: {
    fontSize: 16,
    fontWeight: "500",
    color: "#2B4865",
  },
  menu_aviso: {
    height: height * 0.1,
    width: width * 0.9,
    backgroundColor: "#FCFCFC",
    justifyContent: "space-around",
    // top: (height * 0.040),
    flexDirection: "row",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#E1E1E1",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  menu_aviso_img: {
    width: width * 0.22,
    height: height * 0.1,
    justifyContent: "center", //centro forma vertical
    alignItems: "center", //centro forma horizontal
    // backgroundColor:'purple',
  },
  menu_aviso_texto: {
    width: width * 0.6,
    height: height * 0.1,
    justifyContent: "center", //centro forma vertical
    alignItems: "center", //centro forma horizontal
    flexDirection: "column",
    // backgroundColor:'yellow',
  },
  titulo_aviso: {
    fontWeight: "600",
    fontSize: 16,
    color: "#1A2E35",
    bottom: 5,
  },
  subtitulo_aviso: {
    fontWeight: "500",
    color: "#1A2E35",
  },
  imagen_aviso: {
    height: height * 0.09,
    width: width * 0.21,
    borderRadius: 5,
    resizeMode: "cover",
  },
  textoSlider_dudas: {
    fontSize: 16,
    // textAlign:'center',
    fontWeight: "500",
    color: "#2B4865",
  },
  footer: {
    alignSelf: "center",
    alignItems: "center",
    textAlign: "center",
    position: "absolute", //Here is the trick
    bottom: width * 0.2, //Here is the trick
    borderWidth: 1,
    borderRadius: 5,
  },
  opcionMenu: {
    backgroundColor: "white",
    height: 140,
    justifyContent: "space-evenly",
    flexDirection: "column",
  },
  botonesMenu: {
    backgroundColor: "#ffff",
    height: height * 0.065,
    borderRadius: 4,
    borderWidth: 0.2,
    borderColor: "#FCFCFC",
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
    shadowColor: "#7B8FA1",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 2,
  },
  botonesMenuC: {
    backgroundColor: "#ffff",
    height: height * 0.065,
    borderRadius: 4,
    borderWidth: 0.2,
    borderColor: "#FCFCFC",
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
    shadowColor: "#7B8FA1",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 2,
  },
  textoMenu: {
    fontSize: 15,
    fontWeight: "600",
    color: "#2E86C6",
    marginLeft: 10,
  },
  textoMenuR: {
    fontSize: 15,
    fontWeight: "600",
    color: "#FF6464",
    marginLeft: 10,
  },
  textoTitulo: {
    fontSize: 15,
    fontWeight: "600",
    color: "#6E828A",
    marginLeft: 10,
  },
});

const menu_perfil = StyleSheet.create({
  contenedor: {
    height: height * 1,
    width: width * 1,
    backgroundColor: "white",
    alignItems: "center",
  },
  separador: {
    height: height * 0.02,
  },
  cabecera: {
    // backgroundColor: "tomato",
    width: width * 0.9,
    height: height * 0.15,
    flexDirection: "row",
    justifyContent:'center',
    alignItems:'center',
    // justifyContent:'space-around'
  },
  imagen_logo: {
    width: width * 0.300,
    height: height * 0.145,
    borderRadius:200
  },
  cabecera_derecha: {
    width: width * 0.4,
    // backgroundColor:'pink',
  },
  cabecera_izquierda: {
    width: width * 0.4,
    // backgroundColor:'purple',
  },
  cuerpo: {
    width: width * 0.9,
    height: height * 0.48,
    alignItems: "center",
    // backgroundColor:'yellow',
  },
  containerInputUsuario: {
    borderWidth: 0.4,
    borderRadius: 200,
    borderColor: "#848789",
    // borderBottomWidth:.4,
    alignItems: "center",
    width: width * 0.9,
    height: height * 0.06,
    marginTop: 5,
    marginBottom: 7,
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  textInput: {
    width: width * 0.72,
  },
  text_color: {
    color: "#7F8487",
    fontWeight: "600",
  },
  input_gemeral: {
    // borderRadius:5,
    // borderWidth:1
  },
  seleccionar: {
    width: width * 0.9,
    marginTop: 10,
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: "#D1D1D1",
    backgroundColor: "white",
    fontSize: 13,
  },
  dropdown: {
    fontSize: 15,
  },
  pie: {
    flexDirection: "row",
    width: width * 0.9,
    height: height * 0.1,
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "green",
  },
  perfil_boton_enviar: {
    width: width * 0.87,
    height: height * 0.065,
    backgroundColor: colors.backgroundGeneral,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 7,
  },
  perfil_texto_boton: {
    fontSize: 14,
    fontWeight: "600",
    color: "white",
  },
});

const listado = StyleSheet.create({
  containerLogin: {
    height: height * 1,
    alignItems: "center",
    backgroundColor: "white",
  },
  espaciador: {
    height: height * 0.03,
    // width:  ( width *  0.920 ),
    // alignSelf:'center',
    // justifyContent:'center',
    // alignItems:'center',
  },
  imagen_check: {
    width: width * 0.08,
    height: height * 0.04,
  },
  cuerpo_principal: {
    width: width * 0.95,
    height: height * 0.7,
    // borderWidth:1,
    // borderRadius:3,
    borderColor: "#4D455D",
    // shadowColor: "#000",
    // shadowOffset: {
    //     width: 0,
    //     height: 2,
    // },
    // shadowOpacity: 0.25,
    // shadowRadius: 3.84,
    // elevation: 5,
  },
  cuerpo_principal2: {
    width: width * 0.92,
    height: height * 0.7,
    // borderWidth:.1,
    // borderRadius:3,
    // borderColor:'#4D455D',
    // shadowColor: "#000",
    // shadowOffset: {
    //     width: 0,
    //     height: 2,
    // },
    // shadowOpacity: 0.25,
    // shadowRadius: 3.84,
    // elevation: 5,
  },
  border_item: {
    // margin:5,
    // borderWidth:1,
    // width : (width * 0.520),

    borderRadius: 1,
    // borderColor:'#D6E4E5',
    borderColor: "#000",
    borderWidth: 2,
  },
  contenedor_info: {
    height: height * 0.13,
    width: width * 0.6,
    borderRadius: 5,
    flexDirection: "row",
  },
  lado_izquierdo: {
    // backgroundColor:'tomato',
    width: width * 0.35,
    height: height * 0.13,
    alignSelf: "flex-end",
  },
  lado_derecho: {
    // backgroundColor:'green',
    width: width * 0.3,
    height: height * 0.13,
  },

  texto_info_derecha: {
    color: "#474E68",
    marginLeft: 5,
    fontSize: 13,
    fontWeight: "600",
    textAlign: "left",
  },
  texto_info_derecha_titulo: {
    // marginLeft:10,
    color: "#20262E",
    fontSize: 15,
    fontWeight: "700",
    textAlign: "right",
  },
  texto_info_izquierda: {
    color: "#474E68",
    fontSize: 13,
    fontWeight: "600",
    textAlign: "left",
  },
  texto_info_izquierda_titulo: {
    color: "#20262E",
    marginLeft: 5,
    fontSize: 15,
    fontWeight: "700",
    textAlign: "left",
  },
  contenedorFecha: {
    width: width * 0.95,
    height: height * 0.1,
    backgroundColor: "white",
    borderRadius: 5,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 0.5,
    borderColor: "#f3f3f3",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  contenedorFecha1: {
    // backgroundColor:'red',
    width: width * 0.75,
    height: height * 0.08,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  // contenedorFecha2: {
  //   // backgroundColor:'blue',
  //   width: width * 0.35,
  //   height: height * 0.08,
  //   flexDirection: "row",
  //   justifyContent: "space-around",
  //   alignItems: "center",
  // },
  contenedorFecha3: {
    // backgroundColor:'yellow',
    width: width * 0.15,
    height: height * 0.08,
    justifyContent: "center",
    alignItems: "center",
  },
  resultados: {
    width: width * 0.95,
    // height: height * 0.68,
    // backgroundColor:'blue'
  },
  lis_cuerpo_contenedor: {
    flexDirection: "row",
    justifyContent: "center",
    alignContent: "center",
    backgroundColor: "white",
    marginTop: height * 0.02,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  contenedor_info: {
    // height: height * 0.13,
    width: width * 0.7,
    borderRadius: 5,
    flexDirection: "row",
  },
  lis_col_uno: {
    width: width * 0.1,
    // backgroundColor: "#F2F2F2",
    justifyContent: "center",
    alignItems: "center",
  },
  lis_col_dos: {
    width: width * 0.3,
    // backgroundColor: "#F2F2F2",
  },
  lis_col_tres: {
    width: width * 0.1,
    // backgroundColor: "#F2F2F2",
    justifyContent: "center",
    alignItems: "center",
  },
  // modal listado
  modal_container_gps: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  modal_container_gps_contenedor: {
    width: width * 0.7,
    justifyContent: "center",
    alignSelf: "center",
    borderRadius: 5,
    backgroundColor: "#F0F0F0",
  },
  modal_container_gps_option: {
    borderBottomWidth: 1,
    borderTopWidth: 1,
    borderTopColor: "#ccc",
    borderBottomColor: "#ccc",
    height: height * 0.07,
    justifyContent: "center",
    width: width * 0.69,
    alignItems: "center",
    backgroundColor: "#F5F5F5",
  },
  // modal listado
  lis_boton_opciones: {
    flexDirection: "row",
    width: width * 0.62,
    height: height * 0.06,
    borderRadius:5,
    justifyContent: "space-between",
    alignItems: "center",
    paddingLeft: 10,
    paddingRight: 10,
    borderWidth: 0.2,
},

});

const marcar_asistencia = StyleSheet.create({
  containerLogin: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "white",
  },
  cuadro_biendenida: {
    height: height * 0.2,
    width: width * 0.9,
    // backgroundColor:'red'
  },
  imagen_bienvenida: {
    height: height * 0.2,
    width: width * 0.9,
    // marginTop: height * 0.04,
  },
  fecha_hora: {
    height: height * 0.06,
    width: width * 0.25,
    bottom: height * 0.11,
    backgroundColor: "white",
    alignItems: "center",
    // marginBottom: height * 0.020,
  },
  fecha_texto: {
    fontSize: 17,
    fontFamily: "monospace",
    fontWeight: "600",
  },
  espaciador: {
    height: height * 0.02,
    flexDirection: "row",
  },
  espaciador2: {
    height: height * 0.05,
    flexDirection: "row",

    // backgroundColor:'green'
  },
  text_espaciador: {
    fontSize: 18,
    fontWeight: "500",
  },
  cuerpo_principal: {
    width: width * 0.9,
    height: height * 0.53,
    borderRadius: 5,
    flexDirection: "column",
    justifyContent: "space-around",
    // backgroundColor:'#FAF8F1',
    // marginTop: height * 0.04,
  },
  cuerpo_entrada: {
    width: width * 0.9,
    height: height * 0.12,
    backgroundColor: colors.cuadrosColorMarcar,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 0.5,
    borderRadius: 10,
    borderColor: "#FFFBF5",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 2,
  },
  cuerpo_imagen: {
    width: width * 0.2,
    height: height * 0.1,
    alignItems: "center",
    justifyContent: "center",
  },
  imagen: {
    width: width * 0.13,
    height: height * 0.07,
  },
  imagen_check: {
    width: width * 0.08,
    height: height * 0.04,
  },
  cuerpo_texto: {
    width: width * 0.5,
    height: height * 0.1,
    alignItems: "center",
    justifyContent: "center",
  },
  cuerpo_boton: {
    width: width * 0.2,
    height: height * 0.1,
    alignItems: "center",
    justifyContent: "center",
  },
  cuerpo_refrigerio: {
    width: width * 0.9,
    height: height * 0.1,
    flexDirection: "row",
    alignContent: "center",
    alignItems: "center",
    backgroundColor: colors.cuadrosColorMarcar,
    borderColor: "#4D77FF",
    borderWidth: 0.4,
    borderRadius: 5,
    borderColor: "#FFFBF5",
    borderRadius: 3,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 2,
  },
  cuerpo_salida: {
    width: width * 0.9,
    height: height * 0.1,
    flexDirection: "row",
    alignContent: "center",
    alignItems: "center",
    backgroundColor: colors.cuadrosColorMarcar,
    borderColor: "#4D77FF",
    borderWidth: 0.4,
    borderRadius: 5,
    borderRadius: 5,
    borderColor: "#FFFBF5",
    borderRadius: 3,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 2,
  },
  contenedor_info: {
    // backgroundColor:'#2155CD',
    borderColor: "#03C988",
    borderWidth: 1,
    height: height * 0.1,
    width: width * 0.6,
    borderRadius: 5,
  },
  texto_info: {
    color: "#474E68",
    marginLeft: 5,
    fontSize: 12.4,
    fontWeight: "600",
  },
});

const mis_avisos = StyleSheet.create({
  containerLogin: {
    height: height * 1,
    alignItems: "center",
    backgroundColor: "white",
  },
  espaciador: {
    height: height * 0.02,
    width: width * 0.92,
    alignItems: "center",
  },
  cuerpo_principal: {
    width: width * 0.95,
    height: height * 0.7,
    marginTop: height * 0.02,
    // backgroundColor:'red'
  },
  cuerpo_principal_crear: {
    width: width * 0.98,
    height: height * 0.45,
    marginTop: height * 0.02,
    borderRadius: 10,
    backgroundColor: "#FAFAFA",
    justifyContent: "center",
    alignItems: "center",
  },
  contenedor_info_alerta: {
    height: height * 0.03,
    width: width * 0.7,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  texto_info: {
    color: "#474E68",
    // height: (height * 0.040),
    marginLeft: 5,
    fontSize: 17.4,
    fontWeight: "600",
    // backgroundColor:'tomato'
  },
  dropdown2BtnStyle: {
    width: width * 0.9,
    height: 50,
    borderWidth: 0.5,
    borderColor: "#999999",
    backgroundColor: "white",
    borderRadius: 8,
  },
  alertar: {
    width: width * 1,
    height: height * 0.8,
    backgroundColor: "yellow",
  },
  alertas: {
    width: width * 1,
    height: height * 0.8,
    backgroundColor: "green",
  },
  textarea: {
    borderWidth: 0.5,
    borderColor: "#999999",
    width: width * 0.92,
    borderRadius: 5,
    textAlignVertical: "top",
    paddingLeft: 10,
    paddingTop: 10,
  },
  boton_enviar: {
    height: height * 0.01,
    width: width * 0.9,
  },
  border_item: {
    margin: 5,
    borderWidth: 1,
    borderRadius: 1,
    borderColor: "#D6E4E5",
    // backgroundColor:'#F3EFE0',
  },

  //MODAL INICIO
  modal_container_gps: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  modal_container_gps_contenedor: {
    width: width * 0.7,
    justifyContent: "center",
    alignSelf: "center",
    borderRadius: 5,
    backgroundColor: "#F0F0F0",
  },
  modal_container_gps_option: {
    borderBottomWidth: 1,
    borderTopWidth: 1,
    borderTopColor: "#ccc",
    borderBottomColor: "#ccc",
    height: height * 0.07,
    justifyContent: "center",
    width: width * 0.69,
    alignItems: "center",
    backgroundColor: "#F5F5F5",
  },
  //MODAL FIN
  contenedor_info: {
    height: height * 0.13,
    width: width * 0.72,
    borderRadius: 5,
    flexDirection: "row",
    // backgroundColor:'tomato',
  },
  lado_izquierdo: {
    // backgroundColor:'tomato',
    width: width * 0.35,
    height: height * 0.13,
    alignSelf: "flex-end",
  },
  lado_derecho: {
    // backgroundColor:'green',
    width: width * 0.35,
    height: height * 0.13,
    alignItems: "flex-start",
  },
  avi_boton_opciones: {
    flexDirection: "row",
    width: width * 0.92,
    height: height * 0.05,
    justifyContent: "space-between",
    alignItems: "center",
    paddingLeft: 10,
    paddingRight: 10,
    borderWidth: 0.2,
    borderRadius: 5,
  },
  avi_boton_enviar_view: {
    flexDirection: "row",
    width: width * 0.95,
    height: height * 0.065,
    backgroundColor: colors.botones_bg_color,
    borderRadius: 5,
    marginTop: height * 0.04,
    justifyContent: "center",
    alignItems: "center",
  },
  avi_boton_enviar_tx: {
    color: colors.botones_tx_color,
    fontSize: 16,
  },
  // CUERPO AVISOS INICIO
  avi_cuerpo_notifi: {
    flexDirection: "row",
    width: width * 0.95,
    top: 10,
    borderRadius: 3,
    marginBottom: 15,
    backgroundColor: "#FFFF",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
    // backgroundColor: "red",
  },
  avi_cuerpo_notifi_fila1: {
    flexDirection: "column",
    width: width * 0.15,
    justifyContent: "center",
    alignItems: "center",
  },
  avi_cuerpo_notifi_fila2: {
    flexDirection: "column",
    width: width * 0.68,
    justifyContent: "center",
  },
  avi_cuerpo_notifi_fila3: {
    flexDirection: "column",
    width: width * 0.1,
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  // CUERPO AVISOS FIN
  avi_view_crear_aviso: {
    flexDirection: "row",
    width: width * 0.9,
    height: height * 0.06,
    marginBottom: 10,
    alignItems: "flex-start",
    justifyContent: "flex-end",
  },

  avi_boton_crear_aviso: {
    flexDirection: "row",
    backgroundColor: colors.botones_bg_color_sec,
    width: width * 0.13,
    height: height * 0.065,
    borderRadius: 18,
    marginTop: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  avi_notifi_boton_acp: {
    width: width * 0.14,
    height: height * 0.05,
    borderRadius: 5,
    // backgroundColor: "#44C662",
    justifyContent: "center",
    alignItems: "center",
  },
  avi_notifi_boton_err: {
    width: width * 0.14,
    height: height * 0.05,
    borderRadius: 5,
    // backgroundColor: "#FC4F4F",
    justifyContent: "center",
    alignItems: "center",
  },
  texto_info_derecha: {
    color: "#20262E",
    marginLeft: 5,
    fontSize: 14,
    fontWeight: "600",
    // textAlign:'left'
  },
  avi_titulo_info_aviso: {
    color: "#28518A",
    fontWeight: "500",
  },
  avi_fecha_info_aviso: {
    color: "#8C999A",
  },
  texto_info_derecha_titulo: {
    width: width * 0.7,
    bottom: 10,
    color: "#20262E",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
  },
  texto_info_izquierda: {
    color: "#20262E",
    fontSize: 14,
    fontWeight: "600",
    // textAlign:'left'
  },
  texto_info_izquierda_mensaje: {
    width: width * 0.7,
    // justifyContent:''
    // 434242:'red',
    color: "#73777B",
    marginLeft: 5,
    fontSize: 13,
    fontWeight: "700",
    textAlign: "justify",
    // textAlign:'left'
  },
});

const mis_alertas = StyleSheet.create({
  containerLogin: {
    height: height * 1,
    alignItems: "center",
    backgroundColor: "white",
  },
  espaciador: {
    height: height * 0.02,
    width: width * 0.92,
    alignItems: "center",
  },
  cuerpo_principal: {
    width: width * 0.95,
    height: height * 0.7,
    marginTop: height * 0.02,
    // backgroundColor:'red'
  },
  cuerpo_principal_crear: {
    width: width * 0.98,
    height: height * 0.45,
    marginTop: height * 0.02,
    borderRadius: 10,
    backgroundColor: "#FAFAFA",
    justifyContent: "center",
    alignItems: "center",
  },
  contenedor_info_alerta: {
    height: height * 0.03,
    width: width * 0.7,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  texto_info: {
    color: "#474E68",
    // height: (height * 0.040),
    marginLeft: 5,
    fontSize: 17.4,
    fontWeight: "600",
    // backgroundColor:'tomato'
  },
  dropdown2BtnStyle: {
    width: width * 0.9,
    height: 50,
    borderWidth: 0.5,
    borderColor: "#999999",
    backgroundColor: "white",
    borderRadius: 8,
  },
  alertar: {
    width: width * 1,
    height: height * 0.8,
    backgroundColor: "yellow",
  },
  alertas: {
    width: width * 1,
    height: height * 0.8,
    backgroundColor: "green",
  },
  textarea: {
    borderWidth: 0.5,
    borderColor: "#999999",
    width: width * 0.92,
    borderRadius: 5,
    textAlignVertical: "top",
    paddingLeft: 10,
    paddingTop: 10,
  },
  boton_enviar: {
    height: height * 0.01,
    width: width * 0.9,
  },
  border_item: {
    margin: 5,
    borderWidth: 1,
    borderRadius: 1,
    borderColor: "#D6E4E5",
    // backgroundColor:'#F3EFE0',
  },

  //MODAL INICIO
  modal_container_gps: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  modal_container_gps_contenedor: {
    width: width * 0.7,
    justifyContent: "center",
    alignSelf: "center",
    borderRadius: 5,
    backgroundColor: "#F0F0F0",
  },
  modal_container_gps_option: {
    borderBottomWidth: 1,
    borderTopWidth: 1,
    borderTopColor: "#ccc",
    borderBottomColor: "#ccc",
    height: height * 0.07,
    justifyContent: "center",
    width: width * 0.69,
    alignItems: "center",
    backgroundColor: "#F5F5F5",
  },
  //MODAL FIN
  contenedor_info: {
    height: height * 0.13,
    width: width * 0.72,
    borderRadius: 5,
    flexDirection: "row",
    // backgroundColor:'tomato',
  },
  lado_izquierdo: {
    backgroundColor:'tomato',
    width: width * 0.35,
    height: height * 0.13,
    alignSelf: "flex-end",
  },
  lado_derecho: {
    // backgroundColor:'green',
    width: width * 0.35,
    height: height * 0.13,
    alignItems: "flex-start",
  },
  avi_boton_opciones: {
    flexDirection: "row",
    width: width * 0.92,
    height: height * 0.05,
    justifyContent: "space-between",
    alignItems: "center",
    paddingLeft: 10,
    paddingRight: 10,
    borderWidth: 0.2,
    borderRadius: 5,
  },
  avi_boton_enviar_view: {
    flexDirection: "row",
    width: width * 0.95,
    height: height * 0.065,
    backgroundColor: colors.botones_bg_color,
    borderRadius: 5,
    marginTop: height * 0.04,
    justifyContent: "center",
    alignItems: "center",
  },
  avi_boton_enviar_tx: {
    color: colors.botones_tx_color,
    fontSize: 16,
  },
  // CUERPO AVISOS INICIO
  avi_cuerpo_notifi: {
    flexDirection: "row",
    width: width * 0.95,
    top: 10,
    borderRadius: 3,
    marginBottom: 15,
    backgroundColor: "#FFFF",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
    // backgroundColor: "red",
  },
  avi_cuerpo_notifi_fila1: {
    flexDirection: "column",
    width: width * 0.15,
    justifyContent: "center",
    alignItems: "center",
  },
  avi_cuerpo_notifi_fila2: {
    flexDirection: "column",
    width: width * 0.68,
    justifyContent: "center",
  },
  avi_cuerpo_notifi_fila3: {
    flexDirection: "column",
    width: width * 0.1,
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  // CUERPO AVISOS FIN
  avi_view_crear_aviso: {
    flexDirection: "row",
    width: width * 0.9,
    height: height * 0.06,
    marginBottom: 10,
    alignItems: "flex-start",
    justifyContent: "flex-end",
  },

  avi_boton_crear_aviso: {
    flexDirection: "row",
    backgroundColor: colors.botones_bg_color_sec,
    width: width * 0.13,
    height: height * 0.065,
    borderRadius: 18,
    marginTop: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  avi_notifi_boton_acp: {
    width: width * 0.14,
    height: height * 0.05,
    borderRadius: 5,
    // backgroundColor: "#44C662",
    justifyContent: "center",
    alignItems: "center",
  },
  avi_notifi_boton_err: {
    width: width * 0.14,
    height: height * 0.05,
    borderRadius: 5,
    // backgroundColor: "#FC4F4F",
    justifyContent: "center",
    alignItems: "center",
  },
  texto_info_derecha: {
    color: "#20262E",
    marginLeft: 5,
    fontSize: 14,
    fontWeight: "600",
    // textAlign:'left'
  },
  avi_titulo_info_aviso: {
    color: "#28518A",
    fontWeight: "500",
  },
  avi_fecha_info_aviso: {
    color: "#8C999A",
  },
  texto_info_derecha_titulo: {
    width: width * 0.7,
    bottom: 10,
    color: "#20262E",
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
  },
  texto_info_izquierda: {
    color: "#20262E",
    fontSize: 14,
    fontWeight: "600",
    // textAlign:'left'
  },
  texto_info_izquierda_mensaje: {
    width: width * 0.7,
    // justifyContent:''
    // 434242:'red',
    color: "#73777B",
    marginLeft: 5,
    fontSize: 13,
    fontWeight: "700",
    textAlign: "justify",
    // textAlign:'left'
  },
});

const mi_principal = StyleSheet.create({
  contenedor: {
    height: height * 1,
    width: width * 1,
    alignItems: "center",
    // alignContent:'center',

    backgroundColor: "white",
  },
  espaciador: {
    height: height * 0.04,
    width: width * 0.85,
    // backgroundColor:'red',

    // justifyContent:'flex-start',
    // alignSelf:'flex-start'
    // backgroundColor:'pink',
  },
  imagen_check: {
    width: width * 0.08,
    height: height * 0.04,
  },
  contenedor_menu: {
    width: width * 1,
    height: height * 0.23,
    borderWidth: 0.1,
    backgroundColor: colors.backgroundPanel, //1496DB
    flexDirection: "column",
    alignItems: "center",
  },
  fila1: {
    width: width * 0.93,
    height: height * 0.07,
    borderWidth: 0.1,
    // margin:5,
    backgroundColor: colors.backgroundPanel,
    flexDirection: "row",
    // backgroundColor:'green',
    justifyContent: "space-around",
  },
  izquierdo: {
    width: width * 0.4,
    // backgroundColor:'orange',
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
  },
  derecho: {
    width: width * 0.4,
    // backgroundColor:'tomato',
    alignItems: "flex-end",
    justifyContent: "center",
  },
  menu_imagen: {
    width: width * 0.08,
    height: height * 0.06,
  },
  textoIcono: {
    fontSize: 18,
    color: "white",
    fontWeight: "800",
  },
  cuerpo_principal: {
    width: width * 0.9,
    height: height * 0.5,
    borderWidth: 0.1,
    borderRadius: 3,
    borderColor: "#1496DB",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  fila2: {
    width: width * 0.85,
    height: height * 0.08,
    borderWidth: 0.1,
    backgroundColor: colors.backgroundPanel,
    flexDirection: "row",
    // backgroundColor:'yellow',
    justifyContent: "center",
  },
  containerInputUsuario: {
    // borderWidth:0.5,
    borderRadius: 5,
    // backgroundColor:'rgba(179, 218, 233, 0.9)',
    backgroundColor: "white",
    alignItems: "center",
    width: width * 0.85,
    height: height * 0.07,
    margin: 10,
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  textInput: {
    width: width * 0.6,
    height: height * 0.07,

    // backgroundColor:'red'
  },
  contenedor_opciones: {
    width: width * 0.85,
    height: height * 0.1,
    borderWidth: 0.1,
    borderRadius: 3,
    borderColor: "#4D455D",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  opcion1: {
    backgroundColor: "#0779E4",
    width: width * 0.14,
    height: height * 0.07,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
  },
  opcion2: {
    backgroundColor: "#FF7777",
    width: width * 0.14,
    height: height * 0.07,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
  },
  opcion3: {
    backgroundColor: "#00BD56",
    width: width * 0.14,
    height: height * 0.07,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
  },
  opcion4: {
    backgroundColor: "#064ACB",
    width: width * 0.14,
    height: height * 0.07,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
  },
  contenedor_scroll: {
    width: width * 0.85,
    height: height * 0.4,
    borderWidth: 0.1,
    // backgroundColor:'red',
    borderRadius: 10,
    borderColor: "#4D455D",
    flexDirection: "column",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    // justifyContent:'space-around',
    alignItems: "center",
  },
  scroll_imagen: {
    width: width * 0.85,
    height: height * 0.3,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  detalle: {
    flexDirection: "row",
    backgroundColor: "white",
    width: width * 0.85,
    height: height * 0.1,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    justifyContent: "space-around",
    alignItems: "center",
  },
  detalle1: {
    // height: (height * 0.130),
    width: width * 0.6,
    borderRadius: 5,
    // backgroundColor:'green',
  },
  detalle2: {
    // backgroundColor:'tomato',
    width: width * 0.1,
    height: height * 0.05,
    borderRadius: 200,
    borderWidth: 0.1,
    justifyContent: "center",
    alignItems: "center",
    // height: (height * 0.130),
    backgroundColor: "#EEEEEE",
    borderColor: "#EEEEEE",
  },
  texto_detalle: {
    fontSize: 24,
    color: "#133C52",
    fontWeight: "600",
  },
  subtitulos: {
    fontSize: 14,
    color: "#133C52",
    fontWeight: "600",
  },
  stars: {
    flexDirection: "row",
  },
  texto_stars: {
    fontSize: 13,
    color: "#868686",
  },
  lado_derecho: {
    // backgroundColor:'green',
    width: width * 0.3,
    height: height * 0.13,
  },

  texto_info_derecha: {
    color: "#474E68",
    marginLeft: 5,
    fontSize: 13,
    fontWeight: "600",
    textAlign: "left",
  },
  texto_info_derecha_titulo: {
    // marginLeft:10,
    color: "#20262E",
    fontSize: 15,
    fontWeight: "700",
    textAlign: "right",
  },
  texto_info_izquierda: {
    color: "#474E68",
    fontSize: 13,
    fontWeight: "600",
    textAlign: "left",
  },
  texto_info_izquierda_titulo: {
    color: "#20262E",
    marginLeft: 5,
    fontSize: 15,
    fontWeight: "700",
    textAlign: "left",
  },
});

export {
  login_s,
  menu_index,
  menu_perfil,
  registro,
  listado,
  recuperar_password,
  marcar_asistencia,
  mis_alertas,
  mis_avisos,
  mi_principal,
};
